name: task_manager
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_localized_locales: ^2.0.3
  intl: ^0.18.1
  
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.4
  path_provider: ^2.0.9
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  freezed_annotation: ^2.4.1
  rxdart: ^0.27.3
  uuid: ^4.3.3
  dio: ^5.4.2+1
  connectivity_plus: ^6.0.1
  device_info_plus: ^9.1.2
  jwt_decoder: ^2.0.1
  tuple: ^2.0.0
  auto_route: ^4.0.3
  json_annotation: ^4.4.0
  flutter_secure_storage: ^9.0.0
  get_it: ^7.2.0

  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  awesome_notifications: ^0.8.2

  flutter_svg: ^2.0.10+1
  flutter_map: ^6.1.0
  cached_network_image: ^3.2.0
  declarative_animated_list: ^0.2.0
  percent_indicator: ^4.0.0
  expandable_page_view: ^1.0.10
  tab_indicator_styler: ^2.0.0
  fl_chart: ^0.67.0
  boxy: ^2.0.5
  custom_timer: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.1.7
  freezed: ^2.5.0
  json_serializable: ^6.1.4
  drift_dev: ^2.15.0
  flutter_native_splash: ^2.0.5

flutter_native_splash:
  color: "#F0F2F5"
  color_dark: "#1F1D2C"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/svg/
  
  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/Poppins-Light.ttf
            weight: 300